name: build-apk

on:
  push:
    branches:
      - main
      - github_workflows
      - 'REL-**'
  pull_request:
    branches: [ main ]
jobs:
  build-apk-snapshot:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: cp ~/Downloads/currently_flutter.android.key.properties ./android/key.properties
      - run: flutter build apk --release --no-tree-shake-icons
      - run: ls -la build/app/outputs/flutter-apk/app-release.apk