name: build-apk

on:
  push:
    branches:
      - main
      - github_workflows
      - 'REL-**'
  pull_request:
    branches: [ main ]
jobs:
  flutter-build:
    runs-on: [ self-hosted, macos ]
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
#      - run: flutter gen-l10n
      - run: cp ~/Downloads/currently_flutter.android.key.properties ./android/key.properties
      - run: flutter build apk --release --no-tree-shake-icons
      - run: cp build/app/outputs/flutter-apk/app-release.apk ~/Downloads/currently_local-SNAPSHOT.apk
      - run: ls -la ~/Downloads/currently_local-*